version: 3

tasks:
  tag:latest:
    description: "Tag the current version in git with 'latest'"
    cmds:
      - git describe --tags --abbrev=0
    silent: true
  tag:*:
    description: "Tag the current version in git"
    vars:
      TAG: "{{index .MATCH 0}}"
    cmds:
      - |
        VERSION=$(grep 'version =' taskfile.yaml | head -n 1 | awk '{print $3}' | tr -d '"')
        git tag {{.TAG}}
      - git push origin {{.TAG}}
    silent: true
